version: "3.9"

services:
  ### Go-based services
  go-builder:
    build:
      dockerfile: golang.Dockerfile
    command: bash /usr/bin/go-builder.bash --loop
    volumes:
      # The builder script
      - ./builder/go-builder.bash:/usr/bin/go-builder.bash
      # Volume mounts to watch
      - ./go.mod:/workspace/go.mod
      - ./pkg/:/workspace/pkg/
      - ./services/:/workspace/services/
      # Output Binaries
      - ./genfiles/go-binaries/:/var/go-binaries/
    environment:
      SERVICES: "svc1 svc2 svc3 svc4"

  svc1:
    build:
      dockerfile: golang.Dockerfile
    command: bash /usr/bin/go-runner.bash
    volumes:
      # The runner script
      - ./builder/go-runner.bash:/usr/bin/go-runner.bash
      # Binary location
      - ./genfiles/go-binaries/:/var/go-binaries/
    environment:
      SERVICE_NAME: svc1

  svc2:
    build:
      dockerfile: golang.Dockerfile
    command: bash /usr/bin/go-runner.bash
    volumes:
      # The runner script
      - ./builder/go-runner.bash:/usr/bin/go-runner.bash
      # Binary location
      - ./genfiles/go-binaries/:/var/go-binaries/
    environment:
      SERVICE_NAME: svc2

  svc3:
    build:
      dockerfile: golang.Dockerfile
    command: bash /usr/bin/go-runner.bash
    volumes:
      # The runner script
      - ./builder/go-runner.bash:/usr/bin/go-runner.bash
      # Binary location
      - ./genfiles/go-binaries/:/var/go-binaries/
    environment:
      SERVICE_NAME: svc3

  svc4:
    build:
      dockerfile: golang.Dockerfile
    command: bash /usr/bin/go-runner.bash
    volumes:
      # The runner script
      - ./builder/go-runner.bash:/usr/bin/go-runner.bash
      # Binary location
      - ./genfiles/go-binaries/:/var/go-binaries/
    environment:
      SERVICE_NAME: svc4